#!/bin/sh
#
#
# Munin Plugin to show quagga bgp4 routes

# Standard Config Section Begin ##
  if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
  fi

  if [ "$1" = "config" ]; then

       echo 'graph_title Quagga BGP4 Routes'
       echo 'graph_args --base 1000 -l 0'
       echo 'graph_scale yes'
       echo 'graph_vlabel Received routes via BGP4'
       echo 'graph_category Quagga'
       echo 'bgproutes.label Routes'
       for i in `cat /proc/net/route|grep -v Destination|cut -f1|sort|uniq`; do echo $i.label $i;done
       echo 'graph_info Route information provided by quagga daemon via vtysh'
       exit 0
  fi
# Standard Config Section End ####

# Measure Section Begin ##########
  data=($(vtysh -c "show ip bgp"|grep Total|cut -d" " -f5))

  if [ "$data" = "" ]; then
     echo bgproutes.value    0
  else
     for i in `cat /proc/net/route|grep -v Destination|cut -f1|sort|uniq`;do echo -n $i.value\ ; route -n|grep $i|wc -l;done
     echo bgproutes.value    $data
  fi
# Measure Section ##########

